### ISSUE TITLE
Ascii codec decoding errors

### ISSUE THREAD

**Issue by s0m30n3** [openmaptiles/import-wikidata#2]
I'm currently trying to self-host a map service for my website using a tile server + the OSM Liberty style.
To do that, I have to import some geographic data following the OSM schema.
In the Wikipedia data import step, I get the same warning again and again so I thought it may be a bug and I had to report it. Note that the script does complete but last (summary) line shows missing entries:

```
'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wikidata/etl.py", line 152, in process_json
    page_tuple = get_page(item, pages_bucket)
  File "/usr/local/lib/python2.7/dist-packages/wikidata/etl.py", line 115, in get_page
    if title in pages[lang]:
  File "/usr/local/lib/python2.7/dist-packages/sortedcontainers/sortedlist.py", line 378, in __contains__
    pos = bisect_left(_maxes, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

]

('Parsed {:,} lines.', 51125211)
Loaded 285 of 286 Wikidata IDs and 0 of 9 Wikipedia pages
```

**Comment by eva-j** [comment]
Hi @s0m30n3, sorry for no answer for that long.
Is this still an issue? We haven't seen this kind of message during the processing.

**Comment by s0m30n3** [comment]
Hi @eva-j,
Thanks for taking my bug report into account.
I will take some time this weekend to re-test it and provide more details or if not reproducible asking you to close the bug.

**Comment by s0m30n3** [comment]
I successfully ran ./quickstartsh france (I had to install bc, gawk and make) then make start-tileserver so it works for me. 
As a side note, you should update the README.md to change "git clone git@github.com:openmaptiles/openmaptiles.git" to "git clone https://github.com:openmaptiles/openmaptiles".

Thanks for your amazing work!
I let you close the bug.

**Comment by eva-j** [comment]
Thanks a lot for checking it.
